package com.groot.module.dao;

import com.groot.module.domain.GrootSystemBusheet;
import com.groot.module.domain.GrootSystemBusheetExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GrootSystemBusheetDAOImpl extends SqlMapClientDaoSupport implements GrootSystemBusheetDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootSystemBusheetDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int countByExample(GrootSystemBusheetExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"GROOT_SYSTEM_BUSHEET.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int deleteByExample(GrootSystemBusheetExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("GROOT_SYSTEM_BUSHEET.ibatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		GrootSystemBusheet key = new GrootSystemBusheet();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"GROOT_SYSTEM_BUSHEET.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void insert(GrootSystemBusheet record) {
		getSqlMapClientTemplate().insert(
				"GROOT_SYSTEM_BUSHEET.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void insertSelective(GrootSystemBusheet record) {
		getSqlMapClientTemplate().insert(
				"GROOT_SYSTEM_BUSHEET.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List selectByExample(GrootSystemBusheetExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"GROOT_SYSTEM_BUSHEET.ibatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootSystemBusheet selectByPrimaryKey(String id) {
		GrootSystemBusheet key = new GrootSystemBusheet();
		key.setId(id);
		GrootSystemBusheet record = (GrootSystemBusheet) getSqlMapClientTemplate()
				.queryForObject(
						"GROOT_SYSTEM_BUSHEET.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByExampleSelective(GrootSystemBusheet record,
			GrootSystemBusheetExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("GROOT_SYSTEM_BUSHEET.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByExample(GrootSystemBusheet record,
			GrootSystemBusheetExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"GROOT_SYSTEM_BUSHEET.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByPrimaryKeySelective(GrootSystemBusheet record) {
		int rows = getSqlMapClientTemplate()
				.update("GROOT_SYSTEM_BUSHEET.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByPrimaryKey(GrootSystemBusheet record) {
		int rows = getSqlMapClientTemplate().update(
				"GROOT_SYSTEM_BUSHEET.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static class UpdateByExampleParms extends GrootSystemBusheetExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				GrootSystemBusheetExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}