package com.groot.module.dao;

import com.groot.module.domain.GrootOrderPayment;
import com.groot.module.domain.GrootOrderPaymentExample;
import java.util.List;

public interface GrootOrderPaymentDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int countByExample(GrootOrderPaymentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int deleteByExample(GrootOrderPaymentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	void insert(GrootOrderPayment record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	void insertSelective(GrootOrderPayment record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	List selectByExample(GrootOrderPaymentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	GrootOrderPayment selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByExampleSelective(GrootOrderPayment record,
			GrootOrderPaymentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByExample(GrootOrderPayment record,
			GrootOrderPaymentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByPrimaryKeySelective(GrootOrderPayment record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByPrimaryKey(GrootOrderPayment record);
}