package com.groot.module.dao;

import com.groot.module.domain.GrootSystemRolePermission;
import com.groot.module.domain.GrootSystemRolePermissionExample;
import java.util.List;

public interface GrootSystemRolePermissionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int countByExample(GrootSystemRolePermissionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int deleteByExample(GrootSystemRolePermissionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	void insert(GrootSystemRolePermission record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	void insertSelective(GrootSystemRolePermission record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	List selectByExample(GrootSystemRolePermissionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	GrootSystemRolePermission selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByExampleSelective(GrootSystemRolePermission record,
			GrootSystemRolePermissionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByExample(GrootSystemRolePermission record,
			GrootSystemRolePermissionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByPrimaryKeySelective(GrootSystemRolePermission record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByPrimaryKey(GrootSystemRolePermission record);
}