package com.groot.module.dao;

import com.groot.module.domain.GrootBusheetPermission;
import com.groot.module.domain.GrootBusheetPermissionExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GrootBusheetPermissionDAOImpl extends SqlMapClientDaoSupport implements GrootBusheetPermissionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootBusheetPermissionDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int countByExample(GrootBusheetPermissionExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"GROOT_BUSHEET_PERMISSION.ibatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int deleteByExample(GrootBusheetPermissionExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"GROOT_BUSHEET_PERMISSION.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		GrootBusheetPermission key = new GrootBusheetPermission();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"GROOT_BUSHEET_PERMISSION.ibatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void insert(GrootBusheetPermission record) {
		getSqlMapClientTemplate().insert(
				"GROOT_BUSHEET_PERMISSION.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void insertSelective(GrootBusheetPermission record) {
		getSqlMapClientTemplate().insert(
				"GROOT_BUSHEET_PERMISSION.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List selectByExample(GrootBusheetPermissionExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"GROOT_BUSHEET_PERMISSION.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootBusheetPermission selectByPrimaryKey(String id) {
		GrootBusheetPermission key = new GrootBusheetPermission();
		key.setId(id);
		GrootBusheetPermission record = (GrootBusheetPermission) getSqlMapClientTemplate()
				.queryForObject(
						"GROOT_BUSHEET_PERMISSION.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByExampleSelective(GrootBusheetPermission record,
			GrootBusheetPermissionExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("GROOT_BUSHEET_PERMISSION.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByExample(GrootBusheetPermission record,
			GrootBusheetPermissionExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"GROOT_BUSHEET_PERMISSION.ibatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByPrimaryKeySelective(GrootBusheetPermission record) {
		int rows = getSqlMapClientTemplate()
				.update("GROOT_BUSHEET_PERMISSION.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByPrimaryKey(GrootBusheetPermission record) {
		int rows = getSqlMapClientTemplate().update(
				"GROOT_BUSHEET_PERMISSION.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_BUSHEET_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static class UpdateByExampleParms extends
			GrootBusheetPermissionExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				GrootBusheetPermissionExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}