package com.groot.module.dao;

import com.groot.module.domain.GrootBusheet;
import com.groot.module.domain.GrootBusheetExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GrootBusheetDAOImpl extends SqlMapClientDaoSupport implements GrootBusheetDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootBusheetDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int countByExample(GrootBusheetExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"GROOT_BUSHEET.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int deleteByExample(GrootBusheetExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"GROOT_BUSHEET.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		GrootBusheet key = new GrootBusheet();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"GROOT_BUSHEET.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void insert(GrootBusheet record) {
		getSqlMapClientTemplate().insert(
				"GROOT_BUSHEET.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void insertSelective(GrootBusheet record) {
		getSqlMapClientTemplate().insert(
				"GROOT_BUSHEET.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List selectByExample(GrootBusheetExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"GROOT_BUSHEET.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootBusheet selectByPrimaryKey(String id) {
		GrootBusheet key = new GrootBusheet();
		key.setId(id);
		GrootBusheet record = (GrootBusheet) getSqlMapClientTemplate()
				.queryForObject(
						"GROOT_BUSHEET.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByExampleSelective(GrootBusheet record,
			GrootBusheetExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("GROOT_BUSHEET.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByExample(GrootBusheet record, GrootBusheetExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"GROOT_BUSHEET.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByPrimaryKeySelective(GrootBusheet record) {
		int rows = getSqlMapClientTemplate().update(
				"GROOT_BUSHEET.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByPrimaryKey(GrootBusheet record) {
		int rows = getSqlMapClientTemplate().update(
				"GROOT_BUSHEET.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static class UpdateByExampleParms extends GrootBusheetExample {
		private Object record;

		public UpdateByExampleParms(Object record, GrootBusheetExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}