package com.groot.module.dao;

import com.groot.module.domain.GrootSystemLookupType;
import com.groot.module.domain.GrootSystemLookupTypeExample;
import java.util.List;

public interface GrootSystemLookupTypeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int countByExample(GrootSystemLookupTypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int deleteByExample(GrootSystemLookupTypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	void insert(GrootSystemLookupType record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	void insertSelective(GrootSystemLookupType record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	List selectByExample(GrootSystemLookupTypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	GrootSystemLookupType selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByExampleSelective(GrootSystemLookupType record,
			GrootSystemLookupTypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByExample(GrootSystemLookupType record,
			GrootSystemLookupTypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByPrimaryKeySelective(GrootSystemLookupType record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByPrimaryKey(GrootSystemLookupType record);
}