package com.groot.module.dao;

import com.groot.module.domain.GrootSystemRole;
import com.groot.module.domain.GrootSystemRoleExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GrootSystemRoleDAOImpl extends SqlMapClientDaoSupport implements GrootSystemRoleDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootSystemRoleDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int countByExample(GrootSystemRoleExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"GROOT_SYSTEM_ROLE.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int deleteByExample(GrootSystemRoleExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"GROOT_SYSTEM_ROLE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		GrootSystemRole key = new GrootSystemRole();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"GROOT_SYSTEM_ROLE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void insert(GrootSystemRole record) {
		getSqlMapClientTemplate().insert(
				"GROOT_SYSTEM_ROLE.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void insertSelective(GrootSystemRole record) {
		getSqlMapClientTemplate().insert(
				"GROOT_SYSTEM_ROLE.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List selectByExample(GrootSystemRoleExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"GROOT_SYSTEM_ROLE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootSystemRole selectByPrimaryKey(String id) {
		GrootSystemRole key = new GrootSystemRole();
		key.setId(id);
		GrootSystemRole record = (GrootSystemRole) getSqlMapClientTemplate()
				.queryForObject(
						"GROOT_SYSTEM_ROLE.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByExampleSelective(GrootSystemRole record,
			GrootSystemRoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"GROOT_SYSTEM_ROLE.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByExample(GrootSystemRole record,
			GrootSystemRoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"GROOT_SYSTEM_ROLE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByPrimaryKeySelective(GrootSystemRole record) {
		int rows = getSqlMapClientTemplate()
				.update("GROOT_SYSTEM_ROLE.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByPrimaryKey(GrootSystemRole record) {
		int rows = getSqlMapClientTemplate().update(
				"GROOT_SYSTEM_ROLE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_SYSTEM_ROLE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static class UpdateByExampleParms extends GrootSystemRoleExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				GrootSystemRoleExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}