package com.groot.module.dao;

import com.groot.module.domain.GrootBusheetWorkflow;
import com.groot.module.domain.GrootBusheetWorkflowExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GrootBusheetWorkflowDAOImpl extends SqlMapClientDaoSupport implements GrootBusheetWorkflowDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootBusheetWorkflowDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int countByExample(GrootBusheetWorkflowExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"GROOT_BUSHEET_WORKFLOW.ibatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int deleteByExample(GrootBusheetWorkflowExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"GROOT_BUSHEET_WORKFLOW.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		GrootBusheetWorkflow key = new GrootBusheetWorkflow();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"GROOT_BUSHEET_WORKFLOW.ibatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void insert(GrootBusheetWorkflow record) {
		getSqlMapClientTemplate().insert(
				"GROOT_BUSHEET_WORKFLOW.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void insertSelective(GrootBusheetWorkflow record) {
		getSqlMapClientTemplate().insert(
				"GROOT_BUSHEET_WORKFLOW.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List selectByExample(GrootBusheetWorkflowExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"GROOT_BUSHEET_WORKFLOW.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootBusheetWorkflow selectByPrimaryKey(String id) {
		GrootBusheetWorkflow key = new GrootBusheetWorkflow();
		key.setId(id);
		GrootBusheetWorkflow record = (GrootBusheetWorkflow) getSqlMapClientTemplate()
				.queryForObject(
						"GROOT_BUSHEET_WORKFLOW.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByExampleSelective(GrootBusheetWorkflow record,
			GrootBusheetWorkflowExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("GROOT_BUSHEET_WORKFLOW.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByExample(GrootBusheetWorkflow record,
			GrootBusheetWorkflowExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("GROOT_BUSHEET_WORKFLOW.ibatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByPrimaryKeySelective(GrootBusheetWorkflow record) {
		int rows = getSqlMapClientTemplate()
				.update("GROOT_BUSHEET_WORKFLOW.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public int updateByPrimaryKey(GrootBusheetWorkflow record) {
		int rows = getSqlMapClientTemplate().update(
				"GROOT_BUSHEET_WORKFLOW.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_BUSHEET_WORKFLOW
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static class UpdateByExampleParms extends
			GrootBusheetWorkflowExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				GrootBusheetWorkflowExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}