package com.groot.module.dao;

import com.groot.module.domain.GrootSystemMenu;
import com.groot.module.domain.GrootSystemMenuExample;
import java.util.List;

public interface GrootSystemMenuDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int countByExample(GrootSystemMenuExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int deleteByExample(GrootSystemMenuExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	void insert(GrootSystemMenu record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	void insertSelective(GrootSystemMenu record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	List selectByExample(GrootSystemMenuExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	GrootSystemMenu selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByExampleSelective(GrootSystemMenu record,
			GrootSystemMenuExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByExample(GrootSystemMenu record, GrootSystemMenuExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByPrimaryKeySelective(GrootSystemMenu record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MENU
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByPrimaryKey(GrootSystemMenu record);
}