package com.groot.module.dao;

import com.groot.module.domain.GrootSystemPermission;
import com.groot.module.domain.GrootSystemPermissionExample;
import java.util.List;

public interface GrootSystemPermissionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int countByExample(GrootSystemPermissionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int deleteByExample(GrootSystemPermissionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	void insert(GrootSystemPermission record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	void insertSelective(GrootSystemPermission record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	List selectByExample(GrootSystemPermissionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	GrootSystemPermission selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByExampleSelective(GrootSystemPermission record,
			GrootSystemPermissionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByExample(GrootSystemPermission record,
			GrootSystemPermissionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByPrimaryKeySelective(GrootSystemPermission record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	int updateByPrimaryKey(GrootSystemPermission record);
}