package com.groot.module.domain;

import java.util.Date;
import java.io.Serializable;

public class GrootBusheet implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.busheet_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String busheetName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String createUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.update_user_Id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String updateUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.update_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.csv_templet
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String csvTemplet;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.xls_templet
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String xlsTemplet;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.table_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String tableName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_BUSHEET.busheet_code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String busheetCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.id
	 * @return  the value of GROOT_BUSHEET.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.id
	 * @param id  the value for GROOT_BUSHEET.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.busheet_name
	 * @return  the value of GROOT_BUSHEET.busheet_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getBusheetName() {
		return busheetName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.busheet_name
	 * @param busheetName  the value for GROOT_BUSHEET.busheet_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setBusheetName(String busheetName) {
		this.busheetName = busheetName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.status
	 * @return  the value of GROOT_BUSHEET.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.status
	 * @param status  the value for GROOT_BUSHEET.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.create_user_id
	 * @return  the value of GROOT_BUSHEET.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.create_user_id
	 * @param createUserId  the value for GROOT_BUSHEET.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.create_time
	 * @return  the value of GROOT_BUSHEET.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.create_time
	 * @param createTime  the value for GROOT_BUSHEET.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.update_user_Id
	 * @return  the value of GROOT_BUSHEET.update_user_Id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.update_user_Id
	 * @param updateUserId  the value for GROOT_BUSHEET.update_user_Id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.update_time
	 * @return  the value of GROOT_BUSHEET.update_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.update_time
	 * @param updateTime  the value for GROOT_BUSHEET.update_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.csv_templet
	 * @return  the value of GROOT_BUSHEET.csv_templet
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getCsvTemplet() {
		return csvTemplet;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.csv_templet
	 * @param csvTemplet  the value for GROOT_BUSHEET.csv_templet
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCsvTemplet(String csvTemplet) {
		this.csvTemplet = csvTemplet;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.xls_templet
	 * @return  the value of GROOT_BUSHEET.xls_templet
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getXlsTemplet() {
		return xlsTemplet;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.xls_templet
	 * @param xlsTemplet  the value for GROOT_BUSHEET.xls_templet
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setXlsTemplet(String xlsTemplet) {
		this.xlsTemplet = xlsTemplet;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.table_name
	 * @return  the value of GROOT_BUSHEET.table_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getTableName() {
		return tableName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.table_name
	 * @param tableName  the value for GROOT_BUSHEET.table_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_BUSHEET.busheet_code
	 * @return  the value of GROOT_BUSHEET.busheet_code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getBusheetCode() {
		return busheetCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_BUSHEET.busheet_code
	 * @param busheetCode  the value for GROOT_BUSHEET.busheet_code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setBusheetCode(String busheetCode) {
		this.busheetCode = busheetCode;
	}
}