package com.groot.module.domain;

import java.util.Date;
import java.io.Serializable;

public class GrootSystemConfig implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_CONFIG.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_CONFIG.config_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String configName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_CONFIG.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_CONFIG.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String createUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_CONFIG.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_CONFIG.update_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String updateUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_CONFIG.config_code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String configCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_CONFIG.update_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_CONFIG.REMARK
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_CONFIG.config_value
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String configValue;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_CONFIG
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_CONFIG.id
	 * @return  the value of GROOT_SYSTEM_CONFIG.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_CONFIG.id
	 * @param id  the value for GROOT_SYSTEM_CONFIG.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_CONFIG.config_name
	 * @return  the value of GROOT_SYSTEM_CONFIG.config_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getConfigName() {
		return configName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_CONFIG.config_name
	 * @param configName  the value for GROOT_SYSTEM_CONFIG.config_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setConfigName(String configName) {
		this.configName = configName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_CONFIG.status
	 * @return  the value of GROOT_SYSTEM_CONFIG.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_CONFIG.status
	 * @param status  the value for GROOT_SYSTEM_CONFIG.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_CONFIG.create_user_id
	 * @return  the value of GROOT_SYSTEM_CONFIG.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_CONFIG.create_user_id
	 * @param createUserId  the value for GROOT_SYSTEM_CONFIG.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_CONFIG.create_time
	 * @return  the value of GROOT_SYSTEM_CONFIG.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_CONFIG.create_time
	 * @param createTime  the value for GROOT_SYSTEM_CONFIG.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_CONFIG.update_user_id
	 * @return  the value of GROOT_SYSTEM_CONFIG.update_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_CONFIG.update_user_id
	 * @param updateUserId  the value for GROOT_SYSTEM_CONFIG.update_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_CONFIG.config_code
	 * @return  the value of GROOT_SYSTEM_CONFIG.config_code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getConfigCode() {
		return configCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_CONFIG.config_code
	 * @param configCode  the value for GROOT_SYSTEM_CONFIG.config_code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setConfigCode(String configCode) {
		this.configCode = configCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_CONFIG.update_time
	 * @return  the value of GROOT_SYSTEM_CONFIG.update_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_CONFIG.update_time
	 * @param updateTime  the value for GROOT_SYSTEM_CONFIG.update_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_CONFIG.REMARK
	 * @return  the value of GROOT_SYSTEM_CONFIG.REMARK
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_CONFIG.REMARK
	 * @param remark  the value for GROOT_SYSTEM_CONFIG.REMARK
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_CONFIG.config_value
	 * @return  the value of GROOT_SYSTEM_CONFIG.config_value
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getConfigValue() {
		return configValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_CONFIG.config_value
	 * @param configValue  the value for GROOT_SYSTEM_CONFIG.config_value
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}
}