package com.groot.module.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GrootSystemMonitorExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootSystemMonitorExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected GrootSystemMonitorExample(GrootSystemMonitorExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andCreateUserIdIsNull() {
			addCriterion("create_user_id is null");
			return this;
		}

		public Criteria andCreateUserIdIsNotNull() {
			addCriterion("create_user_id is not null");
			return this;
		}

		public Criteria andCreateUserIdEqualTo(String value) {
			addCriterion("create_user_id =", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotEqualTo(String value) {
			addCriterion("create_user_id <>", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdGreaterThan(String value) {
			addCriterion("create_user_id >", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("create_user_id >=", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdLessThan(String value) {
			addCriterion("create_user_id <", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
			addCriterion("create_user_id <=", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdLike(String value) {
			addCriterion("create_user_id like", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotLike(String value) {
			addCriterion("create_user_id not like", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdIn(List values) {
			addCriterion("create_user_id in", values, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotIn(List values) {
			addCriterion("create_user_id not in", values, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdBetween(String value1, String value2) {
			addCriterion("create_user_id between", value1, value2,
					"createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotBetween(String value1, String value2) {
			addCriterion("create_user_id not between", value1, value2,
					"createUserId");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterion("create_time in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterion("create_time not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andPermissionIsNull() {
			addCriterion("PERMISSION is null");
			return this;
		}

		public Criteria andPermissionIsNotNull() {
			addCriterion("PERMISSION is not null");
			return this;
		}

		public Criteria andPermissionEqualTo(String value) {
			addCriterion("PERMISSION =", value, "permission");
			return this;
		}

		public Criteria andPermissionNotEqualTo(String value) {
			addCriterion("PERMISSION <>", value, "permission");
			return this;
		}

		public Criteria andPermissionGreaterThan(String value) {
			addCriterion("PERMISSION >", value, "permission");
			return this;
		}

		public Criteria andPermissionGreaterThanOrEqualTo(String value) {
			addCriterion("PERMISSION >=", value, "permission");
			return this;
		}

		public Criteria andPermissionLessThan(String value) {
			addCriterion("PERMISSION <", value, "permission");
			return this;
		}

		public Criteria andPermissionLessThanOrEqualTo(String value) {
			addCriterion("PERMISSION <=", value, "permission");
			return this;
		}

		public Criteria andPermissionLike(String value) {
			addCriterion("PERMISSION like", value, "permission");
			return this;
		}

		public Criteria andPermissionNotLike(String value) {
			addCriterion("PERMISSION not like", value, "permission");
			return this;
		}

		public Criteria andPermissionIn(List values) {
			addCriterion("PERMISSION in", values, "permission");
			return this;
		}

		public Criteria andPermissionNotIn(List values) {
			addCriterion("PERMISSION not in", values, "permission");
			return this;
		}

		public Criteria andPermissionBetween(String value1, String value2) {
			addCriterion("PERMISSION between", value1, value2, "permission");
			return this;
		}

		public Criteria andPermissionNotBetween(String value1, String value2) {
			addCriterion("PERMISSION not between", value1, value2, "permission");
			return this;
		}

		public Criteria andMessageIdIsNull() {
			addCriterion("MESSAGE_ID is null");
			return this;
		}

		public Criteria andMessageIdIsNotNull() {
			addCriterion("MESSAGE_ID is not null");
			return this;
		}

		public Criteria andMessageIdEqualTo(String value) {
			addCriterion("MESSAGE_ID =", value, "messageId");
			return this;
		}

		public Criteria andMessageIdNotEqualTo(String value) {
			addCriterion("MESSAGE_ID <>", value, "messageId");
			return this;
		}

		public Criteria andMessageIdGreaterThan(String value) {
			addCriterion("MESSAGE_ID >", value, "messageId");
			return this;
		}

		public Criteria andMessageIdGreaterThanOrEqualTo(String value) {
			addCriterion("MESSAGE_ID >=", value, "messageId");
			return this;
		}

		public Criteria andMessageIdLessThan(String value) {
			addCriterion("MESSAGE_ID <", value, "messageId");
			return this;
		}

		public Criteria andMessageIdLessThanOrEqualTo(String value) {
			addCriterion("MESSAGE_ID <=", value, "messageId");
			return this;
		}

		public Criteria andMessageIdLike(String value) {
			addCriterion("MESSAGE_ID like", value, "messageId");
			return this;
		}

		public Criteria andMessageIdNotLike(String value) {
			addCriterion("MESSAGE_ID not like", value, "messageId");
			return this;
		}

		public Criteria andMessageIdIn(List values) {
			addCriterion("MESSAGE_ID in", values, "messageId");
			return this;
		}

		public Criteria andMessageIdNotIn(List values) {
			addCriterion("MESSAGE_ID not in", values, "messageId");
			return this;
		}

		public Criteria andMessageIdBetween(String value1, String value2) {
			addCriterion("MESSAGE_ID between", value1, value2, "messageId");
			return this;
		}

		public Criteria andMessageIdNotBetween(String value1, String value2) {
			addCriterion("MESSAGE_ID not between", value1, value2, "messageId");
			return this;
		}

		public Criteria andControllerNameIsNull() {
			addCriterion("CONTROLLER_NAME is null");
			return this;
		}

		public Criteria andControllerNameIsNotNull() {
			addCriterion("CONTROLLER_NAME is not null");
			return this;
		}

		public Criteria andControllerNameEqualTo(String value) {
			addCriterion("CONTROLLER_NAME =", value, "controllerName");
			return this;
		}

		public Criteria andControllerNameNotEqualTo(String value) {
			addCriterion("CONTROLLER_NAME <>", value, "controllerName");
			return this;
		}

		public Criteria andControllerNameGreaterThan(String value) {
			addCriterion("CONTROLLER_NAME >", value, "controllerName");
			return this;
		}

		public Criteria andControllerNameGreaterThanOrEqualTo(String value) {
			addCriterion("CONTROLLER_NAME >=", value, "controllerName");
			return this;
		}

		public Criteria andControllerNameLessThan(String value) {
			addCriterion("CONTROLLER_NAME <", value, "controllerName");
			return this;
		}

		public Criteria andControllerNameLessThanOrEqualTo(String value) {
			addCriterion("CONTROLLER_NAME <=", value, "controllerName");
			return this;
		}

		public Criteria andControllerNameLike(String value) {
			addCriterion("CONTROLLER_NAME like", value, "controllerName");
			return this;
		}

		public Criteria andControllerNameNotLike(String value) {
			addCriterion("CONTROLLER_NAME not like", value, "controllerName");
			return this;
		}

		public Criteria andControllerNameIn(List values) {
			addCriterion("CONTROLLER_NAME in", values, "controllerName");
			return this;
		}

		public Criteria andControllerNameNotIn(List values) {
			addCriterion("CONTROLLER_NAME not in", values, "controllerName");
			return this;
		}

		public Criteria andControllerNameBetween(String value1, String value2) {
			addCriterion("CONTROLLER_NAME between", value1, value2,
					"controllerName");
			return this;
		}

		public Criteria andControllerNameNotBetween(String value1, String value2) {
			addCriterion("CONTROLLER_NAME not between", value1, value2,
					"controllerName");
			return this;
		}
	}
}