package com.groot.module.domain;

import java.io.Serializable;

public class GrootSystemRolePermission implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_ROLE_PERMISSION.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_ROLE_PERMISSION.ROLE_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String roleId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_ROLE_PERMISSION.PERMISSION_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String permissionId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_ROLE_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_ROLE_PERMISSION.ID
	 * @return  the value of GROOT_SYSTEM_ROLE_PERMISSION.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_ROLE_PERMISSION.ID
	 * @param id  the value for GROOT_SYSTEM_ROLE_PERMISSION.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_ROLE_PERMISSION.ROLE_ID
	 * @return  the value of GROOT_SYSTEM_ROLE_PERMISSION.ROLE_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_ROLE_PERMISSION.ROLE_ID
	 * @param roleId  the value for GROOT_SYSTEM_ROLE_PERMISSION.ROLE_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_ROLE_PERMISSION.PERMISSION_ID
	 * @return  the value of GROOT_SYSTEM_ROLE_PERMISSION.PERMISSION_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getPermissionId() {
		return permissionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_ROLE_PERMISSION.PERMISSION_ID
	 * @param permissionId  the value for GROOT_SYSTEM_ROLE_PERMISSION.PERMISSION_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setPermissionId(String permissionId) {
		this.permissionId = permissionId;
	}
}