package com.groot.module.domain;

import java.math.BigDecimal;
import java.io.Serializable;

public class GrootSystemLookupCde implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_CDE.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_CDE.type_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String typeId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_CDE.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_CDE.cde_code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String cdeCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_CDE.cde_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String cdeName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_CDE.REMARKS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String remarks;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_CDE.INTEGER_KEY
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private BigDecimal integerKey;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_CDE.id
	 * @return  the value of GROOT_SYSTEM_LOOKUP_CDE.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_CDE.id
	 * @param id  the value for GROOT_SYSTEM_LOOKUP_CDE.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_CDE.type_id
	 * @return  the value of GROOT_SYSTEM_LOOKUP_CDE.type_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_CDE.type_id
	 * @param typeId  the value for GROOT_SYSTEM_LOOKUP_CDE.type_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_CDE.status
	 * @return  the value of GROOT_SYSTEM_LOOKUP_CDE.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_CDE.status
	 * @param status  the value for GROOT_SYSTEM_LOOKUP_CDE.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_CDE.cde_code
	 * @return  the value of GROOT_SYSTEM_LOOKUP_CDE.cde_code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getCdeCode() {
		return cdeCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_CDE.cde_code
	 * @param cdeCode  the value for GROOT_SYSTEM_LOOKUP_CDE.cde_code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCdeCode(String cdeCode) {
		this.cdeCode = cdeCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_CDE.cde_name
	 * @return  the value of GROOT_SYSTEM_LOOKUP_CDE.cde_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getCdeName() {
		return cdeName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_CDE.cde_name
	 * @param cdeName  the value for GROOT_SYSTEM_LOOKUP_CDE.cde_name
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCdeName(String cdeName) {
		this.cdeName = cdeName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_CDE.REMARKS
	 * @return  the value of GROOT_SYSTEM_LOOKUP_CDE.REMARKS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_CDE.REMARKS
	 * @param remarks  the value for GROOT_SYSTEM_LOOKUP_CDE.REMARKS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_CDE.INTEGER_KEY
	 * @return  the value of GROOT_SYSTEM_LOOKUP_CDE.INTEGER_KEY
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public BigDecimal getIntegerKey() {
		return integerKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_CDE.INTEGER_KEY
	 * @param integerKey  the value for GROOT_SYSTEM_LOOKUP_CDE.INTEGER_KEY
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setIntegerKey(BigDecimal integerKey) {
		this.integerKey = integerKey;
	}
}