package com.groot.module.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class GrootSystemUserExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootSystemUserExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected GrootSystemUserExample(GrootSystemUserExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andLoginNameIsNull() {
			addCriterion("LOGIN_NAME is null");
			return this;
		}

		public Criteria andLoginNameIsNotNull() {
			addCriterion("LOGIN_NAME is not null");
			return this;
		}

		public Criteria andLoginNameEqualTo(String value) {
			addCriterion("LOGIN_NAME =", value, "loginName");
			return this;
		}

		public Criteria andLoginNameNotEqualTo(String value) {
			addCriterion("LOGIN_NAME <>", value, "loginName");
			return this;
		}

		public Criteria andLoginNameGreaterThan(String value) {
			addCriterion("LOGIN_NAME >", value, "loginName");
			return this;
		}

		public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
			addCriterion("LOGIN_NAME >=", value, "loginName");
			return this;
		}

		public Criteria andLoginNameLessThan(String value) {
			addCriterion("LOGIN_NAME <", value, "loginName");
			return this;
		}

		public Criteria andLoginNameLessThanOrEqualTo(String value) {
			addCriterion("LOGIN_NAME <=", value, "loginName");
			return this;
		}

		public Criteria andLoginNameLike(String value) {
			addCriterion("LOGIN_NAME like", value, "loginName");
			return this;
		}

		public Criteria andLoginNameNotLike(String value) {
			addCriterion("LOGIN_NAME not like", value, "loginName");
			return this;
		}

		public Criteria andLoginNameIn(List values) {
			addCriterion("LOGIN_NAME in", values, "loginName");
			return this;
		}

		public Criteria andLoginNameNotIn(List values) {
			addCriterion("LOGIN_NAME not in", values, "loginName");
			return this;
		}

		public Criteria andLoginNameBetween(String value1, String value2) {
			addCriterion("LOGIN_NAME between", value1, value2, "loginName");
			return this;
		}

		public Criteria andLoginNameNotBetween(String value1, String value2) {
			addCriterion("LOGIN_NAME not between", value1, value2, "loginName");
			return this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return this;
		}

		public Criteria andPasswordIn(List values) {
			addCriterion("PASSWORD in", values, "password");
			return this;
		}

		public Criteria andPasswordNotIn(List values) {
			addCriterion("PASSWORD not in", values, "password");
			return this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return this;
		}

		public Criteria andRealNameIsNull() {
			addCriterion("REAL_NAME is null");
			return this;
		}

		public Criteria andRealNameIsNotNull() {
			addCriterion("REAL_NAME is not null");
			return this;
		}

		public Criteria andRealNameEqualTo(String value) {
			addCriterion("REAL_NAME =", value, "realName");
			return this;
		}

		public Criteria andRealNameNotEqualTo(String value) {
			addCriterion("REAL_NAME <>", value, "realName");
			return this;
		}

		public Criteria andRealNameGreaterThan(String value) {
			addCriterion("REAL_NAME >", value, "realName");
			return this;
		}

		public Criteria andRealNameGreaterThanOrEqualTo(String value) {
			addCriterion("REAL_NAME >=", value, "realName");
			return this;
		}

		public Criteria andRealNameLessThan(String value) {
			addCriterion("REAL_NAME <", value, "realName");
			return this;
		}

		public Criteria andRealNameLessThanOrEqualTo(String value) {
			addCriterion("REAL_NAME <=", value, "realName");
			return this;
		}

		public Criteria andRealNameLike(String value) {
			addCriterion("REAL_NAME like", value, "realName");
			return this;
		}

		public Criteria andRealNameNotLike(String value) {
			addCriterion("REAL_NAME not like", value, "realName");
			return this;
		}

		public Criteria andRealNameIn(List values) {
			addCriterion("REAL_NAME in", values, "realName");
			return this;
		}

		public Criteria andRealNameNotIn(List values) {
			addCriterion("REAL_NAME not in", values, "realName");
			return this;
		}

		public Criteria andRealNameBetween(String value1, String value2) {
			addCriterion("REAL_NAME between", value1, value2, "realName");
			return this;
		}

		public Criteria andRealNameNotBetween(String value1, String value2) {
			addCriterion("REAL_NAME not between", value1, value2, "realName");
			return this;
		}

		public Criteria andLastLoginTimeIsNull() {
			addCriterion("LAST_LOGIN_TIME is null");
			return this;
		}

		public Criteria andLastLoginTimeIsNotNull() {
			addCriterion("LAST_LOGIN_TIME is not null");
			return this;
		}

		public Criteria andLastLoginTimeEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME =", value, "lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME <>", value,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME >", value, "lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME >=", value,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeLessThan(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME <", value, "lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME <=", value,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeIn(List values) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME in", values,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeNotIn(List values) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME not in", values,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME between", value1, value2,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME not between", value1,
					value2, "lastLoginTime");
			return this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("ROLE_ID is null");
			return this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("ROLE_ID is not null");
			return this;
		}

		public Criteria andRoleIdEqualTo(String value) {
			addCriterion("ROLE_ID =", value, "roleId");
			return this;
		}

		public Criteria andRoleIdNotEqualTo(String value) {
			addCriterion("ROLE_ID <>", value, "roleId");
			return this;
		}

		public Criteria andRoleIdGreaterThan(String value) {
			addCriterion("ROLE_ID >", value, "roleId");
			return this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(String value) {
			addCriterion("ROLE_ID >=", value, "roleId");
			return this;
		}

		public Criteria andRoleIdLessThan(String value) {
			addCriterion("ROLE_ID <", value, "roleId");
			return this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(String value) {
			addCriterion("ROLE_ID <=", value, "roleId");
			return this;
		}

		public Criteria andRoleIdLike(String value) {
			addCriterion("ROLE_ID like", value, "roleId");
			return this;
		}

		public Criteria andRoleIdNotLike(String value) {
			addCriterion("ROLE_ID not like", value, "roleId");
			return this;
		}

		public Criteria andRoleIdIn(List values) {
			addCriterion("ROLE_ID in", values, "roleId");
			return this;
		}

		public Criteria andRoleIdNotIn(List values) {
			addCriterion("ROLE_ID not in", values, "roleId");
			return this;
		}

		public Criteria andRoleIdBetween(String value1, String value2) {
			addCriterion("ROLE_ID between", value1, value2, "roleId");
			return this;
		}

		public Criteria andRoleIdNotBetween(String value1, String value2) {
			addCriterion("ROLE_ID not between", value1, value2, "roleId");
			return this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("PHONE is null");
			return this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("PHONE is not null");
			return this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("PHONE =", value, "phone");
			return this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("PHONE <>", value, "phone");
			return this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("PHONE >", value, "phone");
			return this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("PHONE >=", value, "phone");
			return this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("PHONE <", value, "phone");
			return this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("PHONE <=", value, "phone");
			return this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("PHONE like", value, "phone");
			return this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("PHONE not like", value, "phone");
			return this;
		}

		public Criteria andPhoneIn(List values) {
			addCriterion("PHONE in", values, "phone");
			return this;
		}

		public Criteria andPhoneNotIn(List values) {
			addCriterion("PHONE not in", values, "phone");
			return this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("PHONE between", value1, value2, "phone");
			return this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("PHONE not between", value1, value2, "phone");
			return this;
		}

		public Criteria andTelIsNull() {
			addCriterion("TEL is null");
			return this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("TEL is not null");
			return this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("TEL =", value, "tel");
			return this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("TEL <>", value, "tel");
			return this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("TEL >", value, "tel");
			return this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("TEL >=", value, "tel");
			return this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("TEL <", value, "tel");
			return this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("TEL <=", value, "tel");
			return this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("TEL like", value, "tel");
			return this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("TEL not like", value, "tel");
			return this;
		}

		public Criteria andTelIn(List values) {
			addCriterion("TEL in", values, "tel");
			return this;
		}

		public Criteria andTelNotIn(List values) {
			addCriterion("TEL not in", values, "tel");
			return this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("TEL between", value1, value2, "tel");
			return this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("TEL not between", value1, value2, "tel");
			return this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return this;
		}

		public Criteria andEmailIn(List values) {
			addCriterion("EMAIL in", values, "email");
			return this;
		}

		public Criteria andEmailNotIn(List values) {
			addCriterion("EMAIL not in", values, "email");
			return this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("STATUS in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("STATUS not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return this;
		}

		public Criteria andRemarkIn(List values) {
			addCriterion("REMARK in", values, "remark");
			return this;
		}

		public Criteria andRemarkNotIn(List values) {
			addCriterion("REMARK not in", values, "remark");
			return this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andCreateUserIdIsNull() {
			addCriterion("CREATE_USER_ID is null");
			return this;
		}

		public Criteria andCreateUserIdIsNotNull() {
			addCriterion("CREATE_USER_ID is not null");
			return this;
		}

		public Criteria andCreateUserIdEqualTo(String value) {
			addCriterion("CREATE_USER_ID =", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotEqualTo(String value) {
			addCriterion("CREATE_USER_ID <>", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdGreaterThan(String value) {
			addCriterion("CREATE_USER_ID >", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER_ID >=", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdLessThan(String value) {
			addCriterion("CREATE_USER_ID <", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER_ID <=", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdLike(String value) {
			addCriterion("CREATE_USER_ID like", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotLike(String value) {
			addCriterion("CREATE_USER_ID not like", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdIn(List values) {
			addCriterion("CREATE_USER_ID in", values, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotIn(List values) {
			addCriterion("CREATE_USER_ID not in", values, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdBetween(String value1, String value2) {
			addCriterion("CREATE_USER_ID between", value1, value2,
					"createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER_ID not between", value1, value2,
					"createUserId");
			return this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeIn(List values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotIn(List values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2,
					"updateTime");
			return this;
		}

		public Criteria andUpdateUserIdIsNull() {
			addCriterion("UPDATE_USER_ID is null");
			return this;
		}

		public Criteria andUpdateUserIdIsNotNull() {
			addCriterion("UPDATE_USER_ID is not null");
			return this;
		}

		public Criteria andUpdateUserIdEqualTo(String value) {
			addCriterion("UPDATE_USER_ID =", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdNotEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdGreaterThan(String value) {
			addCriterion("UPDATE_USER_ID >", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdLessThan(String value) {
			addCriterion("UPDATE_USER_ID <", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdLike(String value) {
			addCriterion("UPDATE_USER_ID like", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdNotLike(String value) {
			addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdIn(List values) {
			addCriterion("UPDATE_USER_ID in", values, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdNotIn(List values) {
			addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID between", value1, value2,
					"updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID not between", value1, value2,
					"updateUserId");
			return this;
		}
	}
}