package com.groot.module.domain;

import java.util.Date;
import java.io.Serializable;

public class GrootSystemDepartment implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.DEPARTMENT_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String departmentName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.PARENT_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String parentId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.DEPARTMENT_CODE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String departmentCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.STATUS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.REMARK
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.CREATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.CREATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String createUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.UPDATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_DEPARTMENT.UPDATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String updateUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_DEPARTMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.ID
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.ID
	 * @param id  the value for GROOT_SYSTEM_DEPARTMENT.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.DEPARTMENT_NAME
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.DEPARTMENT_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getDepartmentName() {
		return departmentName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.DEPARTMENT_NAME
	 * @param departmentName  the value for GROOT_SYSTEM_DEPARTMENT.DEPARTMENT_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.USER_ID
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.USER_ID
	 * @param userId  the value for GROOT_SYSTEM_DEPARTMENT.USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.PARENT_ID
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.PARENT_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.PARENT_ID
	 * @param parentId  the value for GROOT_SYSTEM_DEPARTMENT.PARENT_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.DEPARTMENT_CODE
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.DEPARTMENT_CODE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getDepartmentCode() {
		return departmentCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.DEPARTMENT_CODE
	 * @param departmentCode  the value for GROOT_SYSTEM_DEPARTMENT.DEPARTMENT_CODE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.STATUS
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.STATUS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.STATUS
	 * @param status  the value for GROOT_SYSTEM_DEPARTMENT.STATUS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.REMARK
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.REMARK
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.REMARK
	 * @param remark  the value for GROOT_SYSTEM_DEPARTMENT.REMARK
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.CREATE_TIME
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.CREATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.CREATE_TIME
	 * @param createTime  the value for GROOT_SYSTEM_DEPARTMENT.CREATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.CREATE_USER_ID
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.CREATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.CREATE_USER_ID
	 * @param createUserId  the value for GROOT_SYSTEM_DEPARTMENT.CREATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.UPDATE_TIME
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.UPDATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.UPDATE_TIME
	 * @param updateTime  the value for GROOT_SYSTEM_DEPARTMENT.UPDATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_DEPARTMENT.UPDATE_USER_ID
	 * @return  the value of GROOT_SYSTEM_DEPARTMENT.UPDATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_DEPARTMENT.UPDATE_USER_ID
	 * @param updateUserId  the value for GROOT_SYSTEM_DEPARTMENT.UPDATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}
}