package com.groot.module.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GrootSystemBusheetExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootSystemBusheetExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected GrootSystemBusheetExample(GrootSystemBusheetExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return this;
		}

		public Criteria andNameIn(List values) {
			addCriterion("NAME in", values, "name");
			return this;
		}

		public Criteria andNameNotIn(List values) {
			addCriterion("NAME not in", values, "name");
			return this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return this;
		}

		public Criteria andSheetCodeIsNull() {
			addCriterion("SHEET_CODE is null");
			return this;
		}

		public Criteria andSheetCodeIsNotNull() {
			addCriterion("SHEET_CODE is not null");
			return this;
		}

		public Criteria andSheetCodeEqualTo(String value) {
			addCriterion("SHEET_CODE =", value, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeNotEqualTo(String value) {
			addCriterion("SHEET_CODE <>", value, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeGreaterThan(String value) {
			addCriterion("SHEET_CODE >", value, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeGreaterThanOrEqualTo(String value) {
			addCriterion("SHEET_CODE >=", value, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeLessThan(String value) {
			addCriterion("SHEET_CODE <", value, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeLessThanOrEqualTo(String value) {
			addCriterion("SHEET_CODE <=", value, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeLike(String value) {
			addCriterion("SHEET_CODE like", value, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeNotLike(String value) {
			addCriterion("SHEET_CODE not like", value, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeIn(List values) {
			addCriterion("SHEET_CODE in", values, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeNotIn(List values) {
			addCriterion("SHEET_CODE not in", values, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeBetween(String value1, String value2) {
			addCriterion("SHEET_CODE between", value1, value2, "sheetCode");
			return this;
		}

		public Criteria andSheetCodeNotBetween(String value1, String value2) {
			addCriterion("SHEET_CODE not between", value1, value2, "sheetCode");
			return this;
		}

		public Criteria andCsvIsNull() {
			addCriterion("CSV is null");
			return this;
		}

		public Criteria andCsvIsNotNull() {
			addCriterion("CSV is not null");
			return this;
		}

		public Criteria andCsvEqualTo(String value) {
			addCriterion("CSV =", value, "csv");
			return this;
		}

		public Criteria andCsvNotEqualTo(String value) {
			addCriterion("CSV <>", value, "csv");
			return this;
		}

		public Criteria andCsvGreaterThan(String value) {
			addCriterion("CSV >", value, "csv");
			return this;
		}

		public Criteria andCsvGreaterThanOrEqualTo(String value) {
			addCriterion("CSV >=", value, "csv");
			return this;
		}

		public Criteria andCsvLessThan(String value) {
			addCriterion("CSV <", value, "csv");
			return this;
		}

		public Criteria andCsvLessThanOrEqualTo(String value) {
			addCriterion("CSV <=", value, "csv");
			return this;
		}

		public Criteria andCsvLike(String value) {
			addCriterion("CSV like", value, "csv");
			return this;
		}

		public Criteria andCsvNotLike(String value) {
			addCriterion("CSV not like", value, "csv");
			return this;
		}

		public Criteria andCsvIn(List values) {
			addCriterion("CSV in", values, "csv");
			return this;
		}

		public Criteria andCsvNotIn(List values) {
			addCriterion("CSV not in", values, "csv");
			return this;
		}

		public Criteria andCsvBetween(String value1, String value2) {
			addCriterion("CSV between", value1, value2, "csv");
			return this;
		}

		public Criteria andCsvNotBetween(String value1, String value2) {
			addCriterion("CSV not between", value1, value2, "csv");
			return this;
		}

		public Criteria andTableNameIsNull() {
			addCriterion("TABLE_NAME is null");
			return this;
		}

		public Criteria andTableNameIsNotNull() {
			addCriterion("TABLE_NAME is not null");
			return this;
		}

		public Criteria andTableNameEqualTo(String value) {
			addCriterion("TABLE_NAME =", value, "tableName");
			return this;
		}

		public Criteria andTableNameNotEqualTo(String value) {
			addCriterion("TABLE_NAME <>", value, "tableName");
			return this;
		}

		public Criteria andTableNameGreaterThan(String value) {
			addCriterion("TABLE_NAME >", value, "tableName");
			return this;
		}

		public Criteria andTableNameGreaterThanOrEqualTo(String value) {
			addCriterion("TABLE_NAME >=", value, "tableName");
			return this;
		}

		public Criteria andTableNameLessThan(String value) {
			addCriterion("TABLE_NAME <", value, "tableName");
			return this;
		}

		public Criteria andTableNameLessThanOrEqualTo(String value) {
			addCriterion("TABLE_NAME <=", value, "tableName");
			return this;
		}

		public Criteria andTableNameLike(String value) {
			addCriterion("TABLE_NAME like", value, "tableName");
			return this;
		}

		public Criteria andTableNameNotLike(String value) {
			addCriterion("TABLE_NAME not like", value, "tableName");
			return this;
		}

		public Criteria andTableNameIn(List values) {
			addCriterion("TABLE_NAME in", values, "tableName");
			return this;
		}

		public Criteria andTableNameNotIn(List values) {
			addCriterion("TABLE_NAME not in", values, "tableName");
			return this;
		}

		public Criteria andTableNameBetween(String value1, String value2) {
			addCriterion("TABLE_NAME between", value1, value2, "tableName");
			return this;
		}

		public Criteria andTableNameNotBetween(String value1, String value2) {
			addCriterion("TABLE_NAME not between", value1, value2, "tableName");
			return this;
		}

		public Criteria andXlsIsNull() {
			addCriterion("XLS is null");
			return this;
		}

		public Criteria andXlsIsNotNull() {
			addCriterion("XLS is not null");
			return this;
		}

		public Criteria andXlsEqualTo(String value) {
			addCriterion("XLS =", value, "xls");
			return this;
		}

		public Criteria andXlsNotEqualTo(String value) {
			addCriterion("XLS <>", value, "xls");
			return this;
		}

		public Criteria andXlsGreaterThan(String value) {
			addCriterion("XLS >", value, "xls");
			return this;
		}

		public Criteria andXlsGreaterThanOrEqualTo(String value) {
			addCriterion("XLS >=", value, "xls");
			return this;
		}

		public Criteria andXlsLessThan(String value) {
			addCriterion("XLS <", value, "xls");
			return this;
		}

		public Criteria andXlsLessThanOrEqualTo(String value) {
			addCriterion("XLS <=", value, "xls");
			return this;
		}

		public Criteria andXlsLike(String value) {
			addCriterion("XLS like", value, "xls");
			return this;
		}

		public Criteria andXlsNotLike(String value) {
			addCriterion("XLS not like", value, "xls");
			return this;
		}

		public Criteria andXlsIn(List values) {
			addCriterion("XLS in", values, "xls");
			return this;
		}

		public Criteria andXlsNotIn(List values) {
			addCriterion("XLS not in", values, "xls");
			return this;
		}

		public Criteria andXlsBetween(String value1, String value2) {
			addCriterion("XLS between", value1, value2, "xls");
			return this;
		}

		public Criteria andXlsNotBetween(String value1, String value2) {
			addCriterion("XLS not between", value1, value2, "xls");
			return this;
		}
	}
}