package com.groot.module.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GrootOrderPaymentExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootOrderPaymentExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected GrootOrderPaymentExample(GrootOrderPaymentExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_ORDER_PAYMENT
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andOrderNoIsNull() {
			addCriterion("ORDER_NO is null");
			return this;
		}

		public Criteria andOrderNoIsNotNull() {
			addCriterion("ORDER_NO is not null");
			return this;
		}

		public Criteria andOrderNoEqualTo(String value) {
			addCriterion("ORDER_NO =", value, "orderNo");
			return this;
		}

		public Criteria andOrderNoNotEqualTo(String value) {
			addCriterion("ORDER_NO <>", value, "orderNo");
			return this;
		}

		public Criteria andOrderNoGreaterThan(String value) {
			addCriterion("ORDER_NO >", value, "orderNo");
			return this;
		}

		public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_NO >=", value, "orderNo");
			return this;
		}

		public Criteria andOrderNoLessThan(String value) {
			addCriterion("ORDER_NO <", value, "orderNo");
			return this;
		}

		public Criteria andOrderNoLessThanOrEqualTo(String value) {
			addCriterion("ORDER_NO <=", value, "orderNo");
			return this;
		}

		public Criteria andOrderNoLike(String value) {
			addCriterion("ORDER_NO like", value, "orderNo");
			return this;
		}

		public Criteria andOrderNoNotLike(String value) {
			addCriterion("ORDER_NO not like", value, "orderNo");
			return this;
		}

		public Criteria andOrderNoIn(List values) {
			addCriterion("ORDER_NO in", values, "orderNo");
			return this;
		}

		public Criteria andOrderNoNotIn(List values) {
			addCriterion("ORDER_NO not in", values, "orderNo");
			return this;
		}

		public Criteria andOrderNoBetween(String value1, String value2) {
			addCriterion("ORDER_NO between", value1, value2, "orderNo");
			return this;
		}

		public Criteria andOrderNoNotBetween(String value1, String value2) {
			addCriterion("ORDER_NO not between", value1, value2, "orderNo");
			return this;
		}

		public Criteria andOrderTypeIsNull() {
			addCriterion("ORDER_TYPE is null");
			return this;
		}

		public Criteria andOrderTypeIsNotNull() {
			addCriterion("ORDER_TYPE is not null");
			return this;
		}

		public Criteria andOrderTypeEqualTo(String value) {
			addCriterion("ORDER_TYPE =", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeNotEqualTo(String value) {
			addCriterion("ORDER_TYPE <>", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeGreaterThan(String value) {
			addCriterion("ORDER_TYPE >", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_TYPE >=", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeLessThan(String value) {
			addCriterion("ORDER_TYPE <", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeLessThanOrEqualTo(String value) {
			addCriterion("ORDER_TYPE <=", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeLike(String value) {
			addCriterion("ORDER_TYPE like", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeNotLike(String value) {
			addCriterion("ORDER_TYPE not like", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeIn(List values) {
			addCriterion("ORDER_TYPE in", values, "orderType");
			return this;
		}

		public Criteria andOrderTypeNotIn(List values) {
			addCriterion("ORDER_TYPE not in", values, "orderType");
			return this;
		}

		public Criteria andOrderTypeBetween(String value1, String value2) {
			addCriterion("ORDER_TYPE between", value1, value2, "orderType");
			return this;
		}

		public Criteria andOrderTypeNotBetween(String value1, String value2) {
			addCriterion("ORDER_TYPE not between", value1, value2, "orderType");
			return this;
		}

		public Criteria andCardNoIsNull() {
			addCriterion("CARD_NO is null");
			return this;
		}

		public Criteria andCardNoIsNotNull() {
			addCriterion("CARD_NO is not null");
			return this;
		}

		public Criteria andCardNoEqualTo(String value) {
			addCriterion("CARD_NO =", value, "cardNo");
			return this;
		}

		public Criteria andCardNoNotEqualTo(String value) {
			addCriterion("CARD_NO <>", value, "cardNo");
			return this;
		}

		public Criteria andCardNoGreaterThan(String value) {
			addCriterion("CARD_NO >", value, "cardNo");
			return this;
		}

		public Criteria andCardNoGreaterThanOrEqualTo(String value) {
			addCriterion("CARD_NO >=", value, "cardNo");
			return this;
		}

		public Criteria andCardNoLessThan(String value) {
			addCriterion("CARD_NO <", value, "cardNo");
			return this;
		}

		public Criteria andCardNoLessThanOrEqualTo(String value) {
			addCriterion("CARD_NO <=", value, "cardNo");
			return this;
		}

		public Criteria andCardNoLike(String value) {
			addCriterion("CARD_NO like", value, "cardNo");
			return this;
		}

		public Criteria andCardNoNotLike(String value) {
			addCriterion("CARD_NO not like", value, "cardNo");
			return this;
		}

		public Criteria andCardNoIn(List values) {
			addCriterion("CARD_NO in", values, "cardNo");
			return this;
		}

		public Criteria andCardNoNotIn(List values) {
			addCriterion("CARD_NO not in", values, "cardNo");
			return this;
		}

		public Criteria andCardNoBetween(String value1, String value2) {
			addCriterion("CARD_NO between", value1, value2, "cardNo");
			return this;
		}

		public Criteria andCardNoNotBetween(String value1, String value2) {
			addCriterion("CARD_NO not between", value1, value2, "cardNo");
			return this;
		}

		public Criteria andTrxAmtIsNull() {
			addCriterion("TRX_AMT is null");
			return this;
		}

		public Criteria andTrxAmtIsNotNull() {
			addCriterion("TRX_AMT is not null");
			return this;
		}

		public Criteria andTrxAmtEqualTo(BigDecimal value) {
			addCriterion("TRX_AMT =", value, "trxAmt");
			return this;
		}

		public Criteria andTrxAmtNotEqualTo(BigDecimal value) {
			addCriterion("TRX_AMT <>", value, "trxAmt");
			return this;
		}

		public Criteria andTrxAmtGreaterThan(BigDecimal value) {
			addCriterion("TRX_AMT >", value, "trxAmt");
			return this;
		}

		public Criteria andTrxAmtGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("TRX_AMT >=", value, "trxAmt");
			return this;
		}

		public Criteria andTrxAmtLessThan(BigDecimal value) {
			addCriterion("TRX_AMT <", value, "trxAmt");
			return this;
		}

		public Criteria andTrxAmtLessThanOrEqualTo(BigDecimal value) {
			addCriterion("TRX_AMT <=", value, "trxAmt");
			return this;
		}

		public Criteria andTrxAmtIn(List values) {
			addCriterion("TRX_AMT in", values, "trxAmt");
			return this;
		}

		public Criteria andTrxAmtNotIn(List values) {
			addCriterion("TRX_AMT not in", values, "trxAmt");
			return this;
		}

		public Criteria andTrxAmtBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TRX_AMT between", value1, value2, "trxAmt");
			return this;
		}

		public Criteria andTrxAmtNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("TRX_AMT not between", value1, value2, "trxAmt");
			return this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("MOBILE is null");
			return this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("MOBILE is not null");
			return this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("MOBILE =", value, "mobile");
			return this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("MOBILE <>", value, "mobile");
			return this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("MOBILE >", value, "mobile");
			return this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("MOBILE >=", value, "mobile");
			return this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("MOBILE <", value, "mobile");
			return this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("MOBILE <=", value, "mobile");
			return this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("MOBILE like", value, "mobile");
			return this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("MOBILE not like", value, "mobile");
			return this;
		}

		public Criteria andMobileIn(List values) {
			addCriterion("MOBILE in", values, "mobile");
			return this;
		}

		public Criteria andMobileNotIn(List values) {
			addCriterion("MOBILE not in", values, "mobile");
			return this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("MOBILE between", value1, value2, "mobile");
			return this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("MOBILE not between", value1, value2, "mobile");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("STATUS in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("STATUS not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andCompleteTimeIsNull() {
			addCriterion("COMPLETE_TIME is null");
			return this;
		}

		public Criteria andCompleteTimeIsNotNull() {
			addCriterion("COMPLETE_TIME is not null");
			return this;
		}

		public Criteria andCompleteTimeEqualTo(Date value) {
			addCriterion("COMPLETE_TIME =", value, "completeTime");
			return this;
		}

		public Criteria andCompleteTimeNotEqualTo(Date value) {
			addCriterion("COMPLETE_TIME <>", value, "completeTime");
			return this;
		}

		public Criteria andCompleteTimeGreaterThan(Date value) {
			addCriterion("COMPLETE_TIME >", value, "completeTime");
			return this;
		}

		public Criteria andCompleteTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("COMPLETE_TIME >=", value, "completeTime");
			return this;
		}

		public Criteria andCompleteTimeLessThan(Date value) {
			addCriterion("COMPLETE_TIME <", value, "completeTime");
			return this;
		}

		public Criteria andCompleteTimeLessThanOrEqualTo(Date value) {
			addCriterion("COMPLETE_TIME <=", value, "completeTime");
			return this;
		}

		public Criteria andCompleteTimeIn(List values) {
			addCriterion("COMPLETE_TIME in", values, "completeTime");
			return this;
		}

		public Criteria andCompleteTimeNotIn(List values) {
			addCriterion("COMPLETE_TIME not in", values, "completeTime");
			return this;
		}

		public Criteria andCompleteTimeBetween(Date value1, Date value2) {
			addCriterion("COMPLETE_TIME between", value1, value2,
					"completeTime");
			return this;
		}

		public Criteria andCompleteTimeNotBetween(Date value1, Date value2) {
			addCriterion("COMPLETE_TIME not between", value1, value2,
					"completeTime");
			return this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("NOTE is null");
			return this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("NOTE is not null");
			return this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("NOTE =", value, "note");
			return this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("NOTE <>", value, "note");
			return this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("NOTE >", value, "note");
			return this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("NOTE >=", value, "note");
			return this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("NOTE <", value, "note");
			return this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("NOTE <=", value, "note");
			return this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("NOTE like", value, "note");
			return this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("NOTE not like", value, "note");
			return this;
		}

		public Criteria andNoteIn(List values) {
			addCriterion("NOTE in", values, "note");
			return this;
		}

		public Criteria andNoteNotIn(List values) {
			addCriterion("NOTE not in", values, "note");
			return this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("NOTE between", value1, value2, "note");
			return this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("NOTE not between", value1, value2, "note");
			return this;
		}
	}
}