package com.groot.module.domain;

import java.util.Date;
import java.io.Serializable;

public class GrootSystemUser implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.LOGIN_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String loginName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.PASSWORD
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.REAL_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String realName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.LAST_LOGIN_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.ROLE_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String roleId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.PHONE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String phone;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.TEL
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String tel;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.EMAIL
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.STATUS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.REMARK
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.CREATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.CREATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String createUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.UPDATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_USER.UPDATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String updateUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_USER
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.ID
	 * @return  the value of GROOT_SYSTEM_USER.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.ID
	 * @param id  the value for GROOT_SYSTEM_USER.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.LOGIN_NAME
	 * @return  the value of GROOT_SYSTEM_USER.LOGIN_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.LOGIN_NAME
	 * @param loginName  the value for GROOT_SYSTEM_USER.LOGIN_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.PASSWORD
	 * @return  the value of GROOT_SYSTEM_USER.PASSWORD
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.PASSWORD
	 * @param password  the value for GROOT_SYSTEM_USER.PASSWORD
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.REAL_NAME
	 * @return  the value of GROOT_SYSTEM_USER.REAL_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.REAL_NAME
	 * @param realName  the value for GROOT_SYSTEM_USER.REAL_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.LAST_LOGIN_TIME
	 * @return  the value of GROOT_SYSTEM_USER.LAST_LOGIN_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.LAST_LOGIN_TIME
	 * @param lastLoginTime  the value for GROOT_SYSTEM_USER.LAST_LOGIN_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.ROLE_ID
	 * @return  the value of GROOT_SYSTEM_USER.ROLE_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.ROLE_ID
	 * @param roleId  the value for GROOT_SYSTEM_USER.ROLE_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.PHONE
	 * @return  the value of GROOT_SYSTEM_USER.PHONE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.PHONE
	 * @param phone  the value for GROOT_SYSTEM_USER.PHONE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.TEL
	 * @return  the value of GROOT_SYSTEM_USER.TEL
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.TEL
	 * @param tel  the value for GROOT_SYSTEM_USER.TEL
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.EMAIL
	 * @return  the value of GROOT_SYSTEM_USER.EMAIL
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.EMAIL
	 * @param email  the value for GROOT_SYSTEM_USER.EMAIL
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.STATUS
	 * @return  the value of GROOT_SYSTEM_USER.STATUS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.STATUS
	 * @param status  the value for GROOT_SYSTEM_USER.STATUS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.REMARK
	 * @return  the value of GROOT_SYSTEM_USER.REMARK
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.REMARK
	 * @param remark  the value for GROOT_SYSTEM_USER.REMARK
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.CREATE_TIME
	 * @return  the value of GROOT_SYSTEM_USER.CREATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.CREATE_TIME
	 * @param createTime  the value for GROOT_SYSTEM_USER.CREATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.CREATE_USER_ID
	 * @return  the value of GROOT_SYSTEM_USER.CREATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.CREATE_USER_ID
	 * @param createUserId  the value for GROOT_SYSTEM_USER.CREATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.UPDATE_TIME
	 * @return  the value of GROOT_SYSTEM_USER.UPDATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.UPDATE_TIME
	 * @param updateTime  the value for GROOT_SYSTEM_USER.UPDATE_TIME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_USER.UPDATE_USER_ID
	 * @return  the value of GROOT_SYSTEM_USER.UPDATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_USER.UPDATE_USER_ID
	 * @param updateUserId  the value for GROOT_SYSTEM_USER.UPDATE_USER_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}
}