package com.groot.module.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GrootSystemLookupCdeExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootSystemLookupCdeExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected GrootSystemLookupCdeExample(GrootSystemLookupCdeExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_SYSTEM_LOOKUP_CDE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andTypeIdIsNull() {
			addCriterion("type_id is null");
			return this;
		}

		public Criteria andTypeIdIsNotNull() {
			addCriterion("type_id is not null");
			return this;
		}

		public Criteria andTypeIdEqualTo(String value) {
			addCriterion("type_id =", value, "typeId");
			return this;
		}

		public Criteria andTypeIdNotEqualTo(String value) {
			addCriterion("type_id <>", value, "typeId");
			return this;
		}

		public Criteria andTypeIdGreaterThan(String value) {
			addCriterion("type_id >", value, "typeId");
			return this;
		}

		public Criteria andTypeIdGreaterThanOrEqualTo(String value) {
			addCriterion("type_id >=", value, "typeId");
			return this;
		}

		public Criteria andTypeIdLessThan(String value) {
			addCriterion("type_id <", value, "typeId");
			return this;
		}

		public Criteria andTypeIdLessThanOrEqualTo(String value) {
			addCriterion("type_id <=", value, "typeId");
			return this;
		}

		public Criteria andTypeIdLike(String value) {
			addCriterion("type_id like", value, "typeId");
			return this;
		}

		public Criteria andTypeIdNotLike(String value) {
			addCriterion("type_id not like", value, "typeId");
			return this;
		}

		public Criteria andTypeIdIn(List values) {
			addCriterion("type_id in", values, "typeId");
			return this;
		}

		public Criteria andTypeIdNotIn(List values) {
			addCriterion("type_id not in", values, "typeId");
			return this;
		}

		public Criteria andTypeIdBetween(String value1, String value2) {
			addCriterion("type_id between", value1, value2, "typeId");
			return this;
		}

		public Criteria andTypeIdNotBetween(String value1, String value2) {
			addCriterion("type_id not between", value1, value2, "typeId");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("status in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("status not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return this;
		}

		public Criteria andCdeCodeIsNull() {
			addCriterion("cde_code is null");
			return this;
		}

		public Criteria andCdeCodeIsNotNull() {
			addCriterion("cde_code is not null");
			return this;
		}

		public Criteria andCdeCodeEqualTo(String value) {
			addCriterion("cde_code =", value, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeNotEqualTo(String value) {
			addCriterion("cde_code <>", value, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeGreaterThan(String value) {
			addCriterion("cde_code >", value, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeGreaterThanOrEqualTo(String value) {
			addCriterion("cde_code >=", value, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeLessThan(String value) {
			addCriterion("cde_code <", value, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeLessThanOrEqualTo(String value) {
			addCriterion("cde_code <=", value, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeLike(String value) {
			addCriterion("cde_code like", value, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeNotLike(String value) {
			addCriterion("cde_code not like", value, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeIn(List values) {
			addCriterion("cde_code in", values, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeNotIn(List values) {
			addCriterion("cde_code not in", values, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeBetween(String value1, String value2) {
			addCriterion("cde_code between", value1, value2, "cdeCode");
			return this;
		}

		public Criteria andCdeCodeNotBetween(String value1, String value2) {
			addCriterion("cde_code not between", value1, value2, "cdeCode");
			return this;
		}

		public Criteria andCdeNameIsNull() {
			addCriterion("cde_name is null");
			return this;
		}

		public Criteria andCdeNameIsNotNull() {
			addCriterion("cde_name is not null");
			return this;
		}

		public Criteria andCdeNameEqualTo(String value) {
			addCriterion("cde_name =", value, "cdeName");
			return this;
		}

		public Criteria andCdeNameNotEqualTo(String value) {
			addCriterion("cde_name <>", value, "cdeName");
			return this;
		}

		public Criteria andCdeNameGreaterThan(String value) {
			addCriterion("cde_name >", value, "cdeName");
			return this;
		}

		public Criteria andCdeNameGreaterThanOrEqualTo(String value) {
			addCriterion("cde_name >=", value, "cdeName");
			return this;
		}

		public Criteria andCdeNameLessThan(String value) {
			addCriterion("cde_name <", value, "cdeName");
			return this;
		}

		public Criteria andCdeNameLessThanOrEqualTo(String value) {
			addCriterion("cde_name <=", value, "cdeName");
			return this;
		}

		public Criteria andCdeNameLike(String value) {
			addCriterion("cde_name like", value, "cdeName");
			return this;
		}

		public Criteria andCdeNameNotLike(String value) {
			addCriterion("cde_name not like", value, "cdeName");
			return this;
		}

		public Criteria andCdeNameIn(List values) {
			addCriterion("cde_name in", values, "cdeName");
			return this;
		}

		public Criteria andCdeNameNotIn(List values) {
			addCriterion("cde_name not in", values, "cdeName");
			return this;
		}

		public Criteria andCdeNameBetween(String value1, String value2) {
			addCriterion("cde_name between", value1, value2, "cdeName");
			return this;
		}

		public Criteria andCdeNameNotBetween(String value1, String value2) {
			addCriterion("cde_name not between", value1, value2, "cdeName");
			return this;
		}

		public Criteria andRemarksIsNull() {
			addCriterion("REMARKS is null");
			return this;
		}

		public Criteria andRemarksIsNotNull() {
			addCriterion("REMARKS is not null");
			return this;
		}

		public Criteria andRemarksEqualTo(String value) {
			addCriterion("REMARKS =", value, "remarks");
			return this;
		}

		public Criteria andRemarksNotEqualTo(String value) {
			addCriterion("REMARKS <>", value, "remarks");
			return this;
		}

		public Criteria andRemarksGreaterThan(String value) {
			addCriterion("REMARKS >", value, "remarks");
			return this;
		}

		public Criteria andRemarksGreaterThanOrEqualTo(String value) {
			addCriterion("REMARKS >=", value, "remarks");
			return this;
		}

		public Criteria andRemarksLessThan(String value) {
			addCriterion("REMARKS <", value, "remarks");
			return this;
		}

		public Criteria andRemarksLessThanOrEqualTo(String value) {
			addCriterion("REMARKS <=", value, "remarks");
			return this;
		}

		public Criteria andRemarksLike(String value) {
			addCriterion("REMARKS like", value, "remarks");
			return this;
		}

		public Criteria andRemarksNotLike(String value) {
			addCriterion("REMARKS not like", value, "remarks");
			return this;
		}

		public Criteria andRemarksIn(List values) {
			addCriterion("REMARKS in", values, "remarks");
			return this;
		}

		public Criteria andRemarksNotIn(List values) {
			addCriterion("REMARKS not in", values, "remarks");
			return this;
		}

		public Criteria andRemarksBetween(String value1, String value2) {
			addCriterion("REMARKS between", value1, value2, "remarks");
			return this;
		}

		public Criteria andRemarksNotBetween(String value1, String value2) {
			addCriterion("REMARKS not between", value1, value2, "remarks");
			return this;
		}

		public Criteria andIntegerKeyIsNull() {
			addCriterion("INTEGER_KEY is null");
			return this;
		}

		public Criteria andIntegerKeyIsNotNull() {
			addCriterion("INTEGER_KEY is not null");
			return this;
		}

		public Criteria andIntegerKeyEqualTo(BigDecimal value) {
			addCriterion("INTEGER_KEY =", value, "integerKey");
			return this;
		}

		public Criteria andIntegerKeyNotEqualTo(BigDecimal value) {
			addCriterion("INTEGER_KEY <>", value, "integerKey");
			return this;
		}

		public Criteria andIntegerKeyGreaterThan(BigDecimal value) {
			addCriterion("INTEGER_KEY >", value, "integerKey");
			return this;
		}

		public Criteria andIntegerKeyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("INTEGER_KEY >=", value, "integerKey");
			return this;
		}

		public Criteria andIntegerKeyLessThan(BigDecimal value) {
			addCriterion("INTEGER_KEY <", value, "integerKey");
			return this;
		}

		public Criteria andIntegerKeyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("INTEGER_KEY <=", value, "integerKey");
			return this;
		}

		public Criteria andIntegerKeyIn(List values) {
			addCriterion("INTEGER_KEY in", values, "integerKey");
			return this;
		}

		public Criteria andIntegerKeyNotIn(List values) {
			addCriterion("INTEGER_KEY not in", values, "integerKey");
			return this;
		}

		public Criteria andIntegerKeyBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("INTEGER_KEY between", value1, value2, "integerKey");
			return this;
		}

		public Criteria andIntegerKeyNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("INTEGER_KEY not between", value1, value2,
					"integerKey");
			return this;
		}
	}
}