package com.groot.module.domain;

import java.io.Serializable;

public class GrootSystemBusheet implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_BUSHEET.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_BUSHEET.NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_BUSHEET.SHEET_CODE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String sheetCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_BUSHEET.CSV
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String csv;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_BUSHEET.TABLE_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String tableName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_BUSHEET.XLS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String xls;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_BUSHEET
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_BUSHEET.ID
	 * @return  the value of GROOT_SYSTEM_BUSHEET.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_BUSHEET.ID
	 * @param id  the value for GROOT_SYSTEM_BUSHEET.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_BUSHEET.NAME
	 * @return  the value of GROOT_SYSTEM_BUSHEET.NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_BUSHEET.NAME
	 * @param name  the value for GROOT_SYSTEM_BUSHEET.NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_BUSHEET.SHEET_CODE
	 * @return  the value of GROOT_SYSTEM_BUSHEET.SHEET_CODE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getSheetCode() {
		return sheetCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_BUSHEET.SHEET_CODE
	 * @param sheetCode  the value for GROOT_SYSTEM_BUSHEET.SHEET_CODE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setSheetCode(String sheetCode) {
		this.sheetCode = sheetCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_BUSHEET.CSV
	 * @return  the value of GROOT_SYSTEM_BUSHEET.CSV
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getCsv() {
		return csv;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_BUSHEET.CSV
	 * @param csv  the value for GROOT_SYSTEM_BUSHEET.CSV
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCsv(String csv) {
		this.csv = csv;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_BUSHEET.TABLE_NAME
	 * @return  the value of GROOT_SYSTEM_BUSHEET.TABLE_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getTableName() {
		return tableName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_BUSHEET.TABLE_NAME
	 * @param tableName  the value for GROOT_SYSTEM_BUSHEET.TABLE_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_BUSHEET.XLS
	 * @return  the value of GROOT_SYSTEM_BUSHEET.XLS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getXls() {
		return xls;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_BUSHEET.XLS
	 * @param xls  the value for GROOT_SYSTEM_BUSHEET.XLS
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setXls(String xls) {
		this.xls = xls;
	}
}