package com.groot.module.domain;

import java.util.Date;
import java.io.Serializable;

public class GrootSystemMonitor implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_MONITOR.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_MONITOR.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String createUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_MONITOR.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_MONITOR.PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String permission;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_MONITOR.MESSAGE_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String messageId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_MONITOR.CONTROLLER_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String controllerName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_MONITOR.MESSAGE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private byte[] message;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_MONITOR
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_MONITOR.ID
	 * @return  the value of GROOT_SYSTEM_MONITOR.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_MONITOR.ID
	 * @param id  the value for GROOT_SYSTEM_MONITOR.ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_MONITOR.create_user_id
	 * @return  the value of GROOT_SYSTEM_MONITOR.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_MONITOR.create_user_id
	 * @param createUserId  the value for GROOT_SYSTEM_MONITOR.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_MONITOR.create_time
	 * @return  the value of GROOT_SYSTEM_MONITOR.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_MONITOR.create_time
	 * @param createTime  the value for GROOT_SYSTEM_MONITOR.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_MONITOR.PERMISSION
	 * @return  the value of GROOT_SYSTEM_MONITOR.PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getPermission() {
		return permission;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_MONITOR.PERMISSION
	 * @param permission  the value for GROOT_SYSTEM_MONITOR.PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setPermission(String permission) {
		this.permission = permission;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_MONITOR.MESSAGE_ID
	 * @return  the value of GROOT_SYSTEM_MONITOR.MESSAGE_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_MONITOR.MESSAGE_ID
	 * @param messageId  the value for GROOT_SYSTEM_MONITOR.MESSAGE_ID
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_MONITOR.CONTROLLER_NAME
	 * @return  the value of GROOT_SYSTEM_MONITOR.CONTROLLER_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getControllerName() {
		return controllerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_MONITOR.CONTROLLER_NAME
	 * @param controllerName  the value for GROOT_SYSTEM_MONITOR.CONTROLLER_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setControllerName(String controllerName) {
		this.controllerName = controllerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_MONITOR.MESSAGE
	 * @return  the value of GROOT_SYSTEM_MONITOR.MESSAGE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public byte[] getMessage() {
		return message;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_MONITOR.MESSAGE
	 * @param message  the value for GROOT_SYSTEM_MONITOR.MESSAGE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setMessage(byte[] message) {
		this.message = message;
	}
}