package com.groot.module.domain;

import java.util.Date;
import java.io.Serializable;

public class GrootSystemLookupType implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_TYPE.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_TYPE.type_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String typeName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_TYPE.type_Code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String typeCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_TYPE.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_TYPE.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String createUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_TYPE.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column GROOT_SYSTEM_LOOKUP_TYPE.update_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private String updateUserId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_LOOKUP_TYPE
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.id
	 * @return  the value of GROOT_SYSTEM_LOOKUP_TYPE.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.id
	 * @param id  the value for GROOT_SYSTEM_LOOKUP_TYPE.id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.type_NAME
	 * @return  the value of GROOT_SYSTEM_LOOKUP_TYPE.type_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.type_NAME
	 * @param typeName  the value for GROOT_SYSTEM_LOOKUP_TYPE.type_NAME
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.type_Code
	 * @return  the value of GROOT_SYSTEM_LOOKUP_TYPE.type_Code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getTypeCode() {
		return typeCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.type_Code
	 * @param typeCode  the value for GROOT_SYSTEM_LOOKUP_TYPE.type_Code
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.status
	 * @return  the value of GROOT_SYSTEM_LOOKUP_TYPE.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.status
	 * @param status  the value for GROOT_SYSTEM_LOOKUP_TYPE.status
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.create_user_id
	 * @return  the value of GROOT_SYSTEM_LOOKUP_TYPE.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.create_user_id
	 * @param createUserId  the value for GROOT_SYSTEM_LOOKUP_TYPE.create_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.create_time
	 * @return  the value of GROOT_SYSTEM_LOOKUP_TYPE.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.create_time
	 * @param createTime  the value for GROOT_SYSTEM_LOOKUP_TYPE.create_time
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.update_user_id
	 * @return  the value of GROOT_SYSTEM_LOOKUP_TYPE.update_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column GROOT_SYSTEM_LOOKUP_TYPE.update_user_id
	 * @param updateUserId  the value for GROOT_SYSTEM_LOOKUP_TYPE.update_user_id
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}
}