package com.groot.module.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GrootSystemPermissionExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public GrootSystemPermissionExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected GrootSystemPermissionExample(GrootSystemPermissionExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table GROOT_SYSTEM_PERMISSION
	 * @ibatorgenerated  Wed Oct 29 15:35:22 CST 2014
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andPermissionNameIsNull() {
			addCriterion("PERMISSION_NAME is null");
			return this;
		}

		public Criteria andPermissionNameIsNotNull() {
			addCriterion("PERMISSION_NAME is not null");
			return this;
		}

		public Criteria andPermissionNameEqualTo(String value) {
			addCriterion("PERMISSION_NAME =", value, "permissionName");
			return this;
		}

		public Criteria andPermissionNameNotEqualTo(String value) {
			addCriterion("PERMISSION_NAME <>", value, "permissionName");
			return this;
		}

		public Criteria andPermissionNameGreaterThan(String value) {
			addCriterion("PERMISSION_NAME >", value, "permissionName");
			return this;
		}

		public Criteria andPermissionNameGreaterThanOrEqualTo(String value) {
			addCriterion("PERMISSION_NAME >=", value, "permissionName");
			return this;
		}

		public Criteria andPermissionNameLessThan(String value) {
			addCriterion("PERMISSION_NAME <", value, "permissionName");
			return this;
		}

		public Criteria andPermissionNameLessThanOrEqualTo(String value) {
			addCriterion("PERMISSION_NAME <=", value, "permissionName");
			return this;
		}

		public Criteria andPermissionNameLike(String value) {
			addCriterion("PERMISSION_NAME like", value, "permissionName");
			return this;
		}

		public Criteria andPermissionNameNotLike(String value) {
			addCriterion("PERMISSION_NAME not like", value, "permissionName");
			return this;
		}

		public Criteria andPermissionNameIn(List values) {
			addCriterion("PERMISSION_NAME in", values, "permissionName");
			return this;
		}

		public Criteria andPermissionNameNotIn(List values) {
			addCriterion("PERMISSION_NAME not in", values, "permissionName");
			return this;
		}

		public Criteria andPermissionNameBetween(String value1, String value2) {
			addCriterion("PERMISSION_NAME between", value1, value2,
					"permissionName");
			return this;
		}

		public Criteria andPermissionNameNotBetween(String value1, String value2) {
			addCriterion("PERMISSION_NAME not between", value1, value2,
					"permissionName");
			return this;
		}

		public Criteria andPermissionKeyIsNull() {
			addCriterion("PERMISSION_KEY is null");
			return this;
		}

		public Criteria andPermissionKeyIsNotNull() {
			addCriterion("PERMISSION_KEY is not null");
			return this;
		}

		public Criteria andPermissionKeyEqualTo(String value) {
			addCriterion("PERMISSION_KEY =", value, "permissionKey");
			return this;
		}

		public Criteria andPermissionKeyNotEqualTo(String value) {
			addCriterion("PERMISSION_KEY <>", value, "permissionKey");
			return this;
		}

		public Criteria andPermissionKeyGreaterThan(String value) {
			addCriterion("PERMISSION_KEY >", value, "permissionKey");
			return this;
		}

		public Criteria andPermissionKeyGreaterThanOrEqualTo(String value) {
			addCriterion("PERMISSION_KEY >=", value, "permissionKey");
			return this;
		}

		public Criteria andPermissionKeyLessThan(String value) {
			addCriterion("PERMISSION_KEY <", value, "permissionKey");
			return this;
		}

		public Criteria andPermissionKeyLessThanOrEqualTo(String value) {
			addCriterion("PERMISSION_KEY <=", value, "permissionKey");
			return this;
		}

		public Criteria andPermissionKeyLike(String value) {
			addCriterion("PERMISSION_KEY like", value, "permissionKey");
			return this;
		}

		public Criteria andPermissionKeyNotLike(String value) {
			addCriterion("PERMISSION_KEY not like", value, "permissionKey");
			return this;
		}

		public Criteria andPermissionKeyIn(List values) {
			addCriterion("PERMISSION_KEY in", values, "permissionKey");
			return this;
		}

		public Criteria andPermissionKeyNotIn(List values) {
			addCriterion("PERMISSION_KEY not in", values, "permissionKey");
			return this;
		}

		public Criteria andPermissionKeyBetween(String value1, String value2) {
			addCriterion("PERMISSION_KEY between", value1, value2,
					"permissionKey");
			return this;
		}

		public Criteria andPermissionKeyNotBetween(String value1, String value2) {
			addCriterion("PERMISSION_KEY not between", value1, value2,
					"permissionKey");
			return this;
		}

		public Criteria andParentIdIsNull() {
			addCriterion("PARENT_ID is null");
			return this;
		}

		public Criteria andParentIdIsNotNull() {
			addCriterion("PARENT_ID is not null");
			return this;
		}

		public Criteria andParentIdEqualTo(String value) {
			addCriterion("PARENT_ID =", value, "parentId");
			return this;
		}

		public Criteria andParentIdNotEqualTo(String value) {
			addCriterion("PARENT_ID <>", value, "parentId");
			return this;
		}

		public Criteria andParentIdGreaterThan(String value) {
			addCriterion("PARENT_ID >", value, "parentId");
			return this;
		}

		public Criteria andParentIdGreaterThanOrEqualTo(String value) {
			addCriterion("PARENT_ID >=", value, "parentId");
			return this;
		}

		public Criteria andParentIdLessThan(String value) {
			addCriterion("PARENT_ID <", value, "parentId");
			return this;
		}

		public Criteria andParentIdLessThanOrEqualTo(String value) {
			addCriterion("PARENT_ID <=", value, "parentId");
			return this;
		}

		public Criteria andParentIdLike(String value) {
			addCriterion("PARENT_ID like", value, "parentId");
			return this;
		}

		public Criteria andParentIdNotLike(String value) {
			addCriterion("PARENT_ID not like", value, "parentId");
			return this;
		}

		public Criteria andParentIdIn(List values) {
			addCriterion("PARENT_ID in", values, "parentId");
			return this;
		}

		public Criteria andParentIdNotIn(List values) {
			addCriterion("PARENT_ID not in", values, "parentId");
			return this;
		}

		public Criteria andParentIdBetween(String value1, String value2) {
			addCriterion("PARENT_ID between", value1, value2, "parentId");
			return this;
		}

		public Criteria andParentIdNotBetween(String value1, String value2) {
			addCriterion("PARENT_ID not between", value1, value2, "parentId");
			return this;
		}

		public Criteria andPermissionCodeIsNull() {
			addCriterion("PERMISSION_CODE is null");
			return this;
		}

		public Criteria andPermissionCodeIsNotNull() {
			addCriterion("PERMISSION_CODE is not null");
			return this;
		}

		public Criteria andPermissionCodeEqualTo(String value) {
			addCriterion("PERMISSION_CODE =", value, "permissionCode");
			return this;
		}

		public Criteria andPermissionCodeNotEqualTo(String value) {
			addCriterion("PERMISSION_CODE <>", value, "permissionCode");
			return this;
		}

		public Criteria andPermissionCodeGreaterThan(String value) {
			addCriterion("PERMISSION_CODE >", value, "permissionCode");
			return this;
		}

		public Criteria andPermissionCodeGreaterThanOrEqualTo(String value) {
			addCriterion("PERMISSION_CODE >=", value, "permissionCode");
			return this;
		}

		public Criteria andPermissionCodeLessThan(String value) {
			addCriterion("PERMISSION_CODE <", value, "permissionCode");
			return this;
		}

		public Criteria andPermissionCodeLessThanOrEqualTo(String value) {
			addCriterion("PERMISSION_CODE <=", value, "permissionCode");
			return this;
		}

		public Criteria andPermissionCodeLike(String value) {
			addCriterion("PERMISSION_CODE like", value, "permissionCode");
			return this;
		}

		public Criteria andPermissionCodeNotLike(String value) {
			addCriterion("PERMISSION_CODE not like", value, "permissionCode");
			return this;
		}

		public Criteria andPermissionCodeIn(List values) {
			addCriterion("PERMISSION_CODE in", values, "permissionCode");
			return this;
		}

		public Criteria andPermissionCodeNotIn(List values) {
			addCriterion("PERMISSION_CODE not in", values, "permissionCode");
			return this;
		}

		public Criteria andPermissionCodeBetween(String value1, String value2) {
			addCriterion("PERMISSION_CODE between", value1, value2,
					"permissionCode");
			return this;
		}

		public Criteria andPermissionCodeNotBetween(String value1, String value2) {
			addCriterion("PERMISSION_CODE not between", value1, value2,
					"permissionCode");
			return this;
		}

		public Criteria andRequestMappingValueIsNull() {
			addCriterion("REQUEST_MAPPING_VALUE is null");
			return this;
		}

		public Criteria andRequestMappingValueIsNotNull() {
			addCriterion("REQUEST_MAPPING_VALUE is not null");
			return this;
		}

		public Criteria andRequestMappingValueEqualTo(String value) {
			addCriterion("REQUEST_MAPPING_VALUE =", value,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueNotEqualTo(String value) {
			addCriterion("REQUEST_MAPPING_VALUE <>", value,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueGreaterThan(String value) {
			addCriterion("REQUEST_MAPPING_VALUE >", value,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueGreaterThanOrEqualTo(String value) {
			addCriterion("REQUEST_MAPPING_VALUE >=", value,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueLessThan(String value) {
			addCriterion("REQUEST_MAPPING_VALUE <", value,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueLessThanOrEqualTo(String value) {
			addCriterion("REQUEST_MAPPING_VALUE <=", value,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueLike(String value) {
			addCriterion("REQUEST_MAPPING_VALUE like", value,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueNotLike(String value) {
			addCriterion("REQUEST_MAPPING_VALUE not like", value,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueIn(List values) {
			addCriterion("REQUEST_MAPPING_VALUE in", values,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueNotIn(List values) {
			addCriterion("REQUEST_MAPPING_VALUE not in", values,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueBetween(String value1,
				String value2) {
			addCriterion("REQUEST_MAPPING_VALUE between", value1, value2,
					"requestMappingValue");
			return this;
		}

		public Criteria andRequestMappingValueNotBetween(String value1,
				String value2) {
			addCriterion("REQUEST_MAPPING_VALUE not between", value1, value2,
					"requestMappingValue");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("STATUS in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("STATUS not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return this;
		}

		public Criteria andRemarkIn(List values) {
			addCriterion("REMARK in", values, "remark");
			return this;
		}

		public Criteria andRemarkNotIn(List values) {
			addCriterion("REMARK not in", values, "remark");
			return this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andCreateUserIdIsNull() {
			addCriterion("CREATE_USER_ID is null");
			return this;
		}

		public Criteria andCreateUserIdIsNotNull() {
			addCriterion("CREATE_USER_ID is not null");
			return this;
		}

		public Criteria andCreateUserIdEqualTo(String value) {
			addCriterion("CREATE_USER_ID =", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotEqualTo(String value) {
			addCriterion("CREATE_USER_ID <>", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdGreaterThan(String value) {
			addCriterion("CREATE_USER_ID >", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER_ID >=", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdLessThan(String value) {
			addCriterion("CREATE_USER_ID <", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER_ID <=", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdLike(String value) {
			addCriterion("CREATE_USER_ID like", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotLike(String value) {
			addCriterion("CREATE_USER_ID not like", value, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdIn(List values) {
			addCriterion("CREATE_USER_ID in", values, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotIn(List values) {
			addCriterion("CREATE_USER_ID not in", values, "createUserId");
			return this;
		}

		public Criteria andCreateUserIdBetween(String value1, String value2) {
			addCriterion("CREATE_USER_ID between", value1, value2,
					"createUserId");
			return this;
		}

		public Criteria andCreateUserIdNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER_ID not between", value1, value2,
					"createUserId");
			return this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeIn(List values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotIn(List values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2,
					"updateTime");
			return this;
		}

		public Criteria andUpdateUserIdIsNull() {
			addCriterion("UPDATE_USER_ID is null");
			return this;
		}

		public Criteria andUpdateUserIdIsNotNull() {
			addCriterion("UPDATE_USER_ID is not null");
			return this;
		}

		public Criteria andUpdateUserIdEqualTo(String value) {
			addCriterion("UPDATE_USER_ID =", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdNotEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdGreaterThan(String value) {
			addCriterion("UPDATE_USER_ID >", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdLessThan(String value) {
			addCriterion("UPDATE_USER_ID <", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdLike(String value) {
			addCriterion("UPDATE_USER_ID like", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdNotLike(String value) {
			addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdIn(List values) {
			addCriterion("UPDATE_USER_ID in", values, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdNotIn(List values) {
			addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID between", value1, value2,
					"updateUserId");
			return this;
		}

		public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER_ID not between", value1, value2,
					"updateUserId");
			return this;
		}
	}
}